//------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//     Generator      : XSharp.CodeDomProvider 2.20.0.3
//     Timestamp      : 2024/9/18 2:38:52
//     
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
//  </auto-generated>
//------------------------------------------------------------------------------
Begin Namespace CreatingUserControls

    Public Partial Class frmMain

        /// <summary>
        /// Required designer variable.
        /// </summary>
        Private components := Null As System.ComponentModel.IContainer
        Private grpInstructions As System.Windows.Forms.GroupBox
        Private label1 As System.Windows.Forms.Label
        Private dataGridView1 As System.Windows.Forms.DataGridView
        Private cmdSave As System.Windows.Forms.Button
        Private cmdClose As System.Windows.Forms.Button
        Private openFile1 As CreatingUserControls.OpenFile
        Private vcrButtons1 As CreatingUserControls.VCRButtons

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        Protected Override Method Dispose(disposing As Logic) As Void  Strict

            If (disposing .AND. (components != null))
                components:Dispose()
            Endif
            Super:Dispose(disposing)
			Return
        End Method
        #region Windows Form Designer generated Code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
                                                                                                                                                                                                                                                                        Private Method InitializeComponent() As Void Strict
            Local resources := System.ComponentModel.ComponentResourceManager{Typeof(frmMain)} As System.ComponentModel.ComponentResourceManager
            Self:grpInstructions := System.Windows.Forms.GroupBox{}
            Self:label1 := System.Windows.Forms.Label{}
            Self:dataGridView1 := System.Windows.Forms.DataGridView{}
            Self:cmdSave := System.Windows.Forms.Button{}
            Self:cmdClose := System.Windows.Forms.Button{}
            Self:vcrButtons1 := CreatingUserControls.VCRButtons{}
            Self:openFile1 := CreatingUserControls.OpenFile{}
            Self:grpInstructions:SuspendLayout()
            ((System.ComponentModel.ISupportInitialize)(Self:dataGridView1)):BeginInit()
            Self:SuspendLayout()
            // 
            // grpInstructions
            // 
            resources:ApplyResources(Self:grpInstructions, "grpInstructions")
            Self:grpInstructions:Controls:Add(Self:label1)
            Self:grpInstructions:Name := "grpInstructions"
            Self:grpInstructions:TabStop := false
            // 
            // label1
            // 
            resources:ApplyResources(Self:label1, "label1")
            Self:label1:Name := "label1"
            // 
            // dataGridView1
            // 
            resources:ApplyResources(Self:dataGridView1, "dataGridView1")
            Self:dataGridView1:ColumnHeadersHeightSizeMode := System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize
            Self:dataGridView1:Name := "dataGridView1"
            Self:dataGridView1:RowTemplate:Height := 30
            // 
            // cmdSave
            // 
            resources:ApplyResources(Self:cmdSave, "cmdSave")
            Self:cmdSave:Name := "cmdSave"
            Self:cmdSave:UseVisualStyleBackColor := true
            // 
            // cmdClose
            // 
            resources:ApplyResources(Self:cmdClose, "cmdClose")
            Self:cmdClose:Name := "cmdClose"
            Self:cmdClose:UseVisualStyleBackColor := true
            Self:cmdClose:Click += System.EventHandler{ Self, @cmdClose_Click() }
            // 
            // vcrButtons1
            // 
            resources:ApplyResources(Self:vcrButtons1, "vcrButtons1")
            Self:vcrButtons1:Name := "vcrButtons1"
            // 
            // openFile1
            // 
            resources:ApplyResources(Self:openFile1, "openFile1")
            Self:openFile1:DefaultExtension := ".xml"
            Self:openFile1:Filter := "XML files (*.xml)|*.txt|All Files|*.*"
            Self:openFile1:Name := "openFile1"
            // 
            // frmMain
            // 
            resources:ApplyResources(Self, "$this")
            Self:AutoScaleMode := System.Windows.Forms.AutoScaleMode.Font
            Self:Controls:Add(Self:vcrButtons1)
            Self:Controls:Add(Self:openFile1)
            Self:Controls:Add(Self:cmdClose)
            Self:Controls:Add(Self:cmdSave)
            Self:Controls:Add(Self:dataGridView1)
            Self:Controls:Add(Self:grpInstructions)
            Self:Name := "frmMain"
            Self:grpInstructions:ResumeLayout(false)
            ((System.ComponentModel.ISupportInitialize)(Self:dataGridView1)):EndInit()
            Self:ResumeLayout(false)
        End Method
        #endregion
    End Class 
End Namespace
